### ISSUE TITLE
Switch from hugo site to mkdocs site

### ISSUE THREAD

**Issue by adrianhall** [CommunityToolkit/Datasync#235]
Use something like an Read-the-docs theme.

- [ ] Convert the hugo docs site to mkdocs
- [ ] Add in a markdown linter, site builder, and publisher to the github actions
- [ ] Ensure markdown linter action runs on PR in docs/ (check for broken links, etc.)

**Comment by adrianhall** [comment]
Sample github action for publishing c# documentation as markdown:

```yaml
name: Generate Documentation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert XML to Markdown
      run: |
        mkdir -p docs/api
        for xml in $(find src -name '*.xml'); do
          md="docs/api/$(basename ${xml%.xml}.md)"
          pandoc -f docbook -t markdown -o $md $xml
        done

    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: api-docs
        path: docs/api
```

Once this is done, the mkdocs documentation can be built, link checker run, etc.
